### ISSUE TITLE
Make Locale::TextDomain optional

### ISSUE THREAD

**Issue by rehsack** [celogeek/MooX-Options#52]
http://matrix.cpantesters.org/?dist=libintl-perl+1.24 shows impressively how some OS can't use Locale::TextDomain at all. While it's reasonable to push it forward to add a suggestion (recommendations are mandatory for recent CPAN's), requirement is worse.

**Comment by karenetheridge** [comment]
I found this ticket because, indeed, libintl does not install for me on my main development system.  This ticket documents the issues I've had:  https://rt.cpan.org/Ticket/Display.html?id=83980#txn-1597307

I'm not sure why this change was made in the first place, given there are no translations in place for any of the strings?  having locale support in this module is useless if there are no translations. Is the expectation that these would be added in the future?

I'm not sure if locale support adds any value for internal error messages like "Can't find the method <x>". Perhaps for command-line documentation this might be useful, but in that case it is the calling application that would make use of the locale support instead.

**Comment by shadowcat-mst** [comment]
Honestly, I think that a better approach would be a MooX::Options::Localizable that sits atop mainline MooX::Options and provides this feature - that way it can have whatever dependencies it needs without breaking a bunch of existing deployments.

**Comment by karenetheridge** [comment]
It's all the calls to `__x(...)` that are problematic, that come from Locale::TextDomain. MooX::Options would need to define that as an identity function if Locale::TextDomain couldn't be loaded.

**Comment by shadowcat-mst** [comment]
Well, yes. My expectation is that you would instead have a method call, that's identity in base and can be overriden for localisation. In fact, given the lack of any actual localised strings, I'd've thought that just defining

    sub localize_error { $_[1] }

and letting people override that would be quite sufficient.

**Comment by rehsack** [comment]
Since @celogeek gave me repo access - and before I invest lot of thoughts and time in an unexpected/unwanted/unperlish way - what is the suggested way? Creating a dedicated MooX::Options::Localizable or add a hook for localizing?
Maybe a combination of both?
